#!/bin/sh

query="wallpaper" # Give a query to fetch wallpaper

resolution="$(xdpyinfo  | grep -oP 'dimensions:\s+\K\S+')"

orentation="landscape"

#go
cd /home/$USER/.cache
mv wallpaper-cache.jpg wallpaper.jpg

#Setting the lock screen background to the image
gsettings set org.gnome.desktop.screensaver picture-uri-dark file:///home/$USER/.cache/wallpaper.jpg
gsettings set org.gnome.desktop.screensaver picture-uri file:///home/$USER/.cache/wallpaper.jpg

#Setting the desktop background to the image
gsettings set org.gnome.desktop.background picture-uri-dark file:///home/$USER/.cache/wallpaper.jpg
gsettings set org.gnome.desktop.background picture-uri file:///home/$USER/.cache/wallpaper.jpg

#Setting the login screen background to the image
gsettings set org.gnome.login-screen picture-uri-dark file:///home/$USER/.cache/wallpaper.jpg
gsettings set org.gnome.login-screen picture-uri file:///home/$USER/.cache/wallpaper.jpg

#Fetching new wallpaper for future use
curl -Lo wallpaper-cache.jpg -s "https://source.unsplash.com/random/"$(echo $resolution)"/?"$(echo $query),"$(echo $orentation)"
